language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  yarn: true

script:
  - npm i eslint
  - yarn test --coverage
  - yarn build

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    - $FIREBASE_TOKEN
