language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  yarn: true

before_script:
  - npm install -g firebase-tools

script:
  - yarn test --coverage
  - yarn build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
