language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  yarn: true

before_script:
  - npm install firebase-tools -g
  - cd functions && npm install

script:
  - yarn test --coverage
  - npm run build

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    - $FIREBASE_TOKEN
