language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  npm: true

script:
  - npm run build

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    - $FIREBASE_TOKEN
