language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master

cache:
  yarn: true

script:
  - yarn test --coverage
  - yarn build

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
